# .github/workflows/main.yml
name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      # caching the dependency
      - name: 'Cache Dependencies'
        uses: 'actions/cache@v3'
        id: cache-node-modules
        with:
          path: 'node_modules'
          key: deps-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        # only run npm i if cache not found
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn i



      - name: Build application(simulates the deploy)
        run: pm2 restart all
