name: Node Github CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Initialize NVM
        run: |
          export NVM_DIR="/home/runner/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      - name: Set Node.js version
        run: nvm use 18.16.1
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/ecommerce-server
            echo "PATH: $PATH"
            echo "-----------*****----------------"
            ls -al /home/ubuntu/.nvm/versions/node
            echo "-----------*****----------------"
            which pm2
            echo "-----------*****----------------"
            git pull origin main
            /home/ubuntu/.nvm/versions/node/v18.16.1/bin/npm ci
            /home/ubuntu/.yarn/bin/pm2 restart all
