name: Node Github CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      - name: Source NVM and Use Node.js
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 16.20.2
          nvm use 16.20.2
      - name: Check if package-lock.json changed
        id: check_package_lock
        run: echo "::set-output name=changed::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep package-lock.json)"
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/ecommerce-server
            source ~/.nvm/nvm.sh  # Load NVM environment
            nvm use 16.20.2
            git pull origin main
            npm install -g pm2  # Install pm2 globally
            if [[ "${{ steps.check_package_lock.outputs.changed }}" == "package-lock.json" ]]; then
              npm ci  # Install project dependencies using package-lock.json
            fi
            pm2 restart all
      - name: Cache npm dependencies
        if: steps.check_package_lock.outputs.changed == 'package-lock.json'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
